# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: L4js CI & Test

on:
  push:
    branches: [ "feature/*","release/*","bugfix/*" , "develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, '20.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./l4js/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./l4js

      - name: Run Test
        run: npm run test
        working-directory: ./l4js
